Improved non-error output for git commands (#21)
Improve output so it users don't see things that look like errors. E.g.

```
While unsetting http.https://github.com/.extraheader git returned error. Checking error code to determine if credentials were unset.
Error: The process '/usr/bin/git' failed with exit code 5
```